version: "3.7"
services:
  web:
    image: chincheta/mejorvalorados_web:latest
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      MONGO_HOST: mongo
    ports:
      - "5000:5000"
    networks: 
      - mejorvaloradosnet
  publisher:
    image: chincheta/mejorvalorados_publisher:latest
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      RABBITMQ_HOST: rabbitmq
    networks: 
      - mejorvaloradosnet
    secrets:
      - TWITTER_CONSUMER_KEY
      - TWITTER_SECRET
      - TWITTER_ACCESS_TOKEN
      - TWITTER_ACCESS_TOKEN_SECRET
  elmundoes-bot:
    image: chincheta/mejorvalorados_elmundoes-bot:latest
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      RABBITMQ_HOST: rabbitmq
      MONGO_HOST: mongo
    networks:
      - mejorvaloradosnet
  elpaiscom-bot:
    image: chincheta/mejorvalorados_elpaiscom-bot:latest
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      RABBITMQ_HOST: rabbitmq
      MONGO_HOST: mongo
    networks:
      - mejorvaloradosnet
  rabbitmq:
    image: rabbitmq:3
    deploy:
      restart_policy:
        condition: on-failure
    networks: 
      - mejorvaloradosnet
  mongo:
    image: mongo:4
    deploy:
      restart_policy:
        condition: on-failure
    networks: 
      - mejorvaloradosnet

networks: 
  mejorvaloradosnet:

secrets:
  TWITTER_CONSUMER_KEY:
    external: true
  TWITTER_SECRET:
    external: true
  TWITTER_ACCESS_TOKEN:
    external: true
  TWITTER_ACCESS_TOKEN_SECRET:
    external: true
  DISQUS_API_KEY:
    external: true